version: '1'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "j+K>[j]@>nq9CNY)"
      ACCEPT_EULA: "Y"
    ports:
      - '1433:1433'
    expose:
      - '1433'
    restart: unless-stopped


  api:
    build: api/.
    image: api
    restart: unless-stopped
    # environment:
    #   - ASPNETCORE_URLS=http://localhost:8080
    ports: 
      - '8080:80'
    depends_on:
      - sqlserver


  angular:
    build: web/.
    image: web
    ports: 
      - '4200:4200'
    expose:
      - '4200'
    command: >
      bash -c "ng serve --host 0.0.0.0 --port 4200"
    # bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    depends_on:
      - api
    restart: unless-stopped


